Mguillot82/racoonandburgers

app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss

colors changed in _colors and _bootstrap files

colors changed

---

app/assets/stylesheets/config/_bootstrap_variables.scss

change background color on bootstrap scss.

color background change

---

app/assets/stylesheets/config/_fonts.scss
app/controllers/pages_controller.rb
app/views/pages/style.html.erb
config/routes.rb

Font dedifinition 
+ Add a page to test the style modification

font definition

---

app/assets/stylesheets/config/_bootstrap_variables.scss
app/views/pages/style.html.erb

Change in the bootstrap buttons ==> we can use them

button creation

---

Gemfile
Gemfile.lock
app/assets/stylesheets/config/_bootstrap_variables.scss
app/controllers/application_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
config/environments/development.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20230529142922_add_devise_to_users.rb
db/schema.rb
test/controllers/users_controller_test.rb

Excessive talent was needed to perform this magnificent application controller

Application Controller done like a pro dont try this at home

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_index.scss
app/views/pages/style.html.erb

racoon cards

---

app/views/pages/style.html.erb

footer fix

---

app/views/pages/style.html.erb

add test pages/style

---

app/controllers/pages_controller.rb
app/views/components/_navbar.html.erb

devise fix + navbar log in log out fix

devise fix + navbar log in log out fix

---

app/controllers/application_controller.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb

Modification of params authorized and the forms for creation and modification of account

params authorized + modification of forms

---

app/models/user.rb

belongs_to :service changed with has_one :service to fix sign in issues

associations fixed in user model

---

.gitignore
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
db/migrate/20230530103115_change_racoon.rb
db/schema.rb

modif racoon

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_avatar.scss
app/controllers/application_controller.rb
app/models/user.rb
app/views/components/_navbar.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
config/environments/development.rb
config/environments/production.rb
config/storage.yml
db/migrate/20230530105245_create_active_storage_tables.active_storage.rb
db/schema.rb

cloudinary install

---

app/controllers/services_controller.rb
app/controllers/users_controller.rb
app/views/services/_form.html.erb
app/views/services/destroy.html.erb
app/views/services/edit.html.erb
app/views/services/new.html.erb
app/views/services/update.html.erb
app/views/users/show.html.erb
test/controllers/services_controller_test.rb

Ajout des controller et des view de user et service

controller et view user + service

---

app/controllers/disponibilities_controller.rb
app/models/disponibility.rb
db/migrate/20230531101627_add_status_to_disponibilities.rb
db/schema.rb

column status added to disponibilities
model dispo : enum added

status add and dispo modified

---

app/controllers/racoons_controller.rb
app/controllers/services_controller.rb
app/models/disponibility.rb
app/models/service.rb
app/views/components/_navbar.html.erb
app/views/racoons/show.html.erb
app/views/services/_form.html.erb
app/views/services/edit.html.erb
app/views/users/show.html.erb
test/controllers/racoons_controller_test.rb

services fix

---

app/assets/stylesheets/application.scss
app/controllers/disponibilities_controller.rb
app/controllers/racoons_controller.rb
app/controllers/reservations_controller.rb
app/javascript/controllers/flatpickr_controller.js
app/javascript/controllers/index.js
app/models/disponibility.rb
app/views/disponibilities/_form.html.erb
app/views/disponibilities/new.html.erb
app/views/racoons/show.html.erb
config/routes.rb
db/migrate/20230531131537_add_status_default.rb
db/schema.rb
package.json
test/controllers/reservations_controller_test.rb
yarn.lock

Several modifications but still on going

disponibility and reservation ongoing

---

app/controllers/disponibilities_controller.rb
app/controllers/reservations_controller.rb
app/models/disponibility.rb
app/views/reservations/show.html.erb
config/routes.rb
db/schema.rb

reservation finalized

---

app/controllers/racoons_controller.rb
app/views/racoons/show.html.erb
app/views/services/_form.html.erb
app/views/services/new.html.erb

link + service fix

---

app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb

remove racoon checkbox in registration

remove racoon checkbox in registration

---

app/controllers/disponibilities_controller.rb
app/controllers/racoons_controller.rb
app/controllers/services_controller.rb
app/controllers/users_controller.rb
app/models/reservation.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/racoons/show.html.erb
app/views/users/dashboard.html.erb
app/views/users/show.html.erb
config/routes.rb

dashboard creation

---

app/controllers/reservations_controller.rb
app/views/users/dashboard.html.erb

dashboard check

---

app/controllers/reservations_controller.rb
app/models/reservation.rb
app/views/users/dashboard.html.erb
config/routes.rb

status reservation
